### ISSUE TITLE
error: cannot find symbol variable menu

### ISSUE THREAD

**Issue by chilupa** [udacity/and-nd-firebase#13]
This was the error while I'm trying to run my app. It is showing me error here. 
`error: cannot find symbol variable menu`

Can you please help me in solving this. I'm unable to figure out. 
```
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.main_menu, menu);
        return true;
    }
```

**When I performed** `gradlew build --stacktrace`, **This was the Stack trace i got**. 
```
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\FirebaseApps\WeCare\app\src\main\java\com\pc\wecare\MainActivity.java:120: error: cannot find symbol
        inflater.inflate(R.menu.main_menu, menu);
                          ^
  symbol:   variable menu
  location: class R
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by notdrone-1** [comment]
Make sure you have [this file](https://github.com/udacity/and-nd-firebase/blob/1.00-starting-point/app/src/main/res/menu/main_menu.xml) inside your `menu` folder.

**Comment by al130m** [comment]
what did you mean menu folder

**Comment by MarkBozinovic** [comment]
The res folder? If not there, to create a menu file, is that correct?
