### ISSUE TITLE
Cannot resolve symbol 'R'

### ISSUE THREAD

**Issue by adiaholic** [udacity/and-nd-firebase#39]
Whenever tried to add 
compile 'com.google.firebase:firebase-core:15.0.0'
it gives an error

**Comment by rjwest** [comment]
This seemed the work for me when I had this error;

make sure in your firebase build.gradle, under dependencies you have:
 `classpath 'com.google.gms:google-services:3.3.1'`

with the most recent version of google services (mine being 3.3.1), as soon as I did this and re-synced everything ran smoothly again

Keep in mind I am using firebase-core:15.0.2

**Comment by adiaholic** [comment]
Thanks for that !

**Comment by Kashish-Sharma** [comment]
Or you can select sync files with gradle on menu bar of Android studio

**Comment by raghibislam** [comment]
Android resource linking failed
Output:  C:\Users\user\AndroidStudioProjects\MyApplication\app\src\main\res\layout\activity_main2.xml:10: error: attribute layout_constraintHorizonta_bias (aka com.example.codebind.myapplication:layout_constraintHorizonta_bias) not found.
error: failed linking file resources.

Command: C:\Users\user\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\2aa1a50b275688b3c8017d916765ab19\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\user\AppData\Local\Android\Sdk\platforms\android-28\android.jar\
        --manifest\
        C:\Users\user\AndroidStudioProjects\MyApplication\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\user\AndroidStudioProjects\MyApplication\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\user\AndroidStudioProjects\MyApplication\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\user\AndroidStudioProjects\MyApplication\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        com.example.codebind.myapplication\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\user\AndroidStudioProjects\MyApplication\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
